name: Build and Test

on:
  push:
    branches:
      - '*' # matches every branch
  pull_request:
    branches:
      - '*' # matches every branch


jobs:
  linux:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - if: ${{ github.repository_owner == 'Snowtrack' || github.repository_owner == 'snowtrack' }}
        name: Discord Message
        uses: appleboy/discord-action@master
        with:
          webhook_id: ${{ secrets.WEBHOOK_ID }}
          webhook_token: ${{ secrets.WEBHOOK_TOKEN }}
          color: "#48f442"
          username: "GitHub Bot"
          message: "A new commit has been pushed."

  macos:
    runs-on: macos-latest
    timeout-minutes: 15
    steps:
    
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          lfs: true
          node-version: 12
      - name: Checkout LFS objects
        run: git lfs pull
      - uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}
      - run: npm install

      - name: Run Tests
        run: npm run ava

      - name: Coveralls GitHub Action
        uses: coverallsapp/github-action@v1.1.2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: npm run tsc, build
        run: |
          npm run tsc
          npm run build
          mkdir -p dist/out-tsc/node_modules/drivelist/build/Release/
          mv dist/out-tsc/main-macos dist/out-tsc/snow
          cp node_modules/drivelist/build/Release/drivelist.node dist/out-tsc/node_modules/drivelist/build/Release/drivelist.node

      - name: Publish Artifact
        uses: actions/upload-artifact@v2
        with:
          name: snow-cli-darwin-x64.zip
          path: |
            dist/out-tsc/snow
            dist/out-tsc/node_modules/drivelist/build/Release/drivelist.node


  windows:
    runs-on: windows-latest
    timeout-minutes: 15
    steps:
    
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          lfs: true
          node-version: 12
      - name: Checkout LFS objects
        run: git lfs pull
      - uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}
      - run: npm install

      - name: Run Tests
        run: npm run ava

      - name: Coveralls GitHub Action
        uses: coverallsapp/github-action@v1.1.2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: npm run tsc, build
        run: |
          npm run tsc
          npm run build
          mkdir -p dist/out-tsc/node_modules/drivelist/build/Release/
          mv dist/out-tsc/main-win.exe dist/out-tsc/snow.exe
          cp node_modules/drivelist/build/Release/drivelist.node dist/out-tsc/node_modules/drivelist/build/Release/drivelist.node

      - name: Publish Artifact
        uses: actions/upload-artifact@v2
        with:
          name: snow-cli-win-x64.zip
          path: |
            dist/out-tsc/snow.exe
            dist/out-tsc/node_modules/drivelist/build/Release/drivelist.node